"""add_immutable_audit_history_table

Revision ID: 0654532c4c0b
Revises: 36c61eb0e8ea
Create Date: 2026-05-04 01:20:03.137494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.crypto


# revision identifiers, used by Alembic.
revision: str = '0654532c4c0b'
down_revision: Union[str, Sequence[str], None] = '36c61eb0e8ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profiles_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('old_first_name', sa.String(length=100), nullable=False),
    sa.Column('old_last_name', sa.String(length=100), nullable=False),
    sa.Column('old_date_of_birth', sa.Date(), nullable=False),
    sa.Column('old_medical_history', app.crypto.EncryptedString(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_profiles_history')
    # ### end Alembic commands ###
