"""Add server default for users.created

Revision ID: 1c9a32119d8b
Revises: 55ba7122f04f
Create Date: 2026-05-10 02:13:39.662280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c9a32119d8b'
down_revision: Union[str, Sequence[str], None] = '55ba7122f04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles_history', sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('patient_profiles_history', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles_history', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('patient_profiles_history', 'changed_at')
    # ### end Alembic commands ###
