"""Add server defaults for created_at and update timestamps

Revision ID: 3336e12668b9
Revises: 1c9a32119d8b
Create Date: 2026-05-10 02:45:54.249133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3336e12668b9'
down_revision: Union[str, Sequence[str], None] = '1c9a32119d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
