"""add_immutable_audit_history_table

Revision ID: 36c61eb0e8ea
Revises: 3131d2bf5df7
Create Date: 2026-05-04 01:00:26.468969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c61eb0e8ea'
down_revision: Union[str, Sequence[str], None] = '3131d2bf5df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
