"""Encrypted Database Schema

Revision ID: 7ff00e9c1064
Revises: 90fcc8251e75
Create Date: 2026-05-09 22:54:57.641230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.crypto import EncryptedString


# revision identifiers, used by Alembic.
revision: str = '7ff00e9c1064'
down_revision: Union[str, Sequence[str], None] = '90fcc8251e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.alter_column('patient_profiles', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=EncryptedString(),
               existing_nullable=False)
    op.alter_column('patient_profiles', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=EncryptedString(),
               existing_nullable=False)
    op.alter_column('patient_profiles_history', 'old_first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=EncryptedString(),
               existing_nullable=False)
    op.alter_column('patient_profiles_history', 'old_last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=EncryptedString(),
               existing_nullable=False)
    op.add_column('users', sa.Column('is_password_set', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('activation_token_jti', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'activation_token_jti')
    op.drop_column('users', 'is_password_set')
    op.alter_column('patient_profiles_history', 'old_last_name',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('patient_profiles_history', 'old_first_name',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('patient_profiles', 'last_name',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('patient_profiles', 'first_name',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('patient_profiles', 'version')
    # ### end Alembic commands ###
